### ISSUE TITLE
Frequent crashes in scalismoLab

### ISSUE THREAD

**Issue by embeh** [unibas-gravis/scalismo#231] opened 2018-02-14 11:29 UTC
On a Win7 x64 system, running JRE 1.8.0, I get very frequent crashes when trying out the first tutorials.

Steps:
1.) Double-click launch_windows.bat to start scalismoLab
2.) Open Documents > Fast Track > Rigid Alignment
3.) Select the first piece of code in the tutorial window (val mesh : ... ) and hit Shift-Enter to execute
4.) Wait for a few seconds, moving the mouse back and forth between the three windows  --> crash

Attached are two log files
[hs_err_pid8796.log](https://github.com/unibas-gravis/scalismo/files/1723709/hs_err_pid8796.log)
[hs_err_pid11008.log](https://github.com/unibas-gravis/scalismo/files/1723710/hs_err_pid11008.log)

**Comment by marcelluethi** [comment] 2018-02-14 11:46
Thanks for reporting this issue and for the detailed log. 

It seems that it is due to a problem with JavaFX. As Windows 7 is quite old (mainstream support from Microsoft has ended), we will need to figure out if we can (and want) do something about it.  But in any case it is very useful to know about this issue and we will see if we can find a quick solution. 

As this bug only affects ScalismoLab (and not Scalismo) I will close the issue here, but will keep you posted if we find something out.

**Closed by marcelluethi** 2018-02-14 11:46 UTC

**Comment by embeh** [comment] 2018-02-14 11:55
Fair enough. I'd just like to point out that a.) Win7 is still very common (https://en.wikipedia.org/wiki/Usage_share_of_operating_systems#Desktop_and_laptop_computers or  http://gs.statcounter.com/os-version-market-share/windows/desktop/worldwide), and b.) these crashes will largely prevent participation in the upcoming online course.

**Comment by marcelluethi** [comment] 2018-02-14 12:15
Yes I know that people are still using it - and we really appreciate that you reported it. The reason I closed the issue is not that we won't look into it, but because the bug does not affect scalismo itself. 

ScalismoLab is a tiny layer on top of [Scalismo-ui](https://github.com/unibas-gravis/scalismo-ui). It currently is not open source, hence there is no good place to reopen the issue.

**Comment by marcelluethi** [comment] 2018-02-21 08:09
@embeh An update regarding the crashes. It seems that these crashes happen only with very specific versions of the Java Runtime Environment. To prevent a user from having such a bad experience, we have bundled the JRE together with ScalismoLab. You can find an updated version of ScalismoLab, which uses the approprate JVM here: http://shapemodelling.cs.unibas.ch/scalismolab-win64.zip

**Comment by embeh** [comment] 2018-02-21 20:04
Great, thank you! Just in time for the course. Will try tomorrow.
