### ISSUE TITLE
importing meshes with duplicated vertices

### ISSUE THREAD

**Issue by mads79** [unibas-gravis/scalismo#234] opened 2018-04-09 09:14 UTC
I have a set of meshes with correspondence, but as an artefact of the registration process, a number of the vertices are overlapping in each mesh.
When I import the meshes with DataCollection.fromMeshDirectory the overlapping vertices are removed, and I end up with a different number of points in each mesh, and consequently there is no longer any correspondence?
What is the correct way to solve it? 
It would be nice to have a option not to eliminate vertices in the mesh import functions.

**Comment by marcelluethi** [comment] 2018-04-09 14:34
The issue comes from the .stl format. It cannot represent two distinct points, which have the same coordinates. The solution would be to save the meshes in the .vtk format. 

We have debated the issues with .stl earlier. On one hand, stl is in such widespread use  (and hence supported by many programs) that we cannot get around it. On the other hand, it causes this kind of problems. No decision on whether we will drop .stl altogether, and with what to replace it has been taken. We are happy for any input / recommendations regarding this issue.

**Comment by mads79** [comment] 2018-04-09 16:14
Good point - I didn't realize stl gave coordinates for each vertex for each loop, but I see the problem now.

I agree that the ability to load stl is a must, because you can be quite constrained in where you get your data from. Personally I would be fine if you could  load stl, but only save vtk file; essentially making scalismo work only with vtk but providing a conversion tool to get started. (I don't know if I'm representative, though, I can imagine a lot of people might be more picky about how they use the output of scalismo, and would be unhappy to have an extra conversion step after). 

I am curious how you work around the problem though? Do you just make sure to use a coarser mesh for the reference than the target when you do registration, or what is the trick?

**Comment by marcelluethi** [comment] 2018-04-10 20:18
@mads79 The best workaround is to save all the meshes after registration in vtk format. The vtk format will happily distinct points with the same coordinates. 

If you need to use the stl format, you should make sure that the reference surface that you use for building the model is nicely meshes, I.e. it does not have duplicate points or points which are very close together.

**Comment by guatavita** [comment] 2018-05-08 00:42
I have found the same problem, using both VTK and STL format.

You can have different number of points between a VTK and a STL format when you have "invisible holes" inside your VTK. For example, if you have holes inside your VTK and you apply a Smoothing or Connectivity Filter, the connection of the small part inside your VTK will be invisible. But, the points will still be there. The conversion from VTK to STL remove these unconnected points. 

Hope this precision will help somebody.

**Comment by guatavita** [comment] 2018-05-08 00:48
Moreover, in order to reduce the complexity of your registration framework. You can pre-process your VTK meshes with a "vtkWindowedSincPolyDataFilter" and also re-mesh them with ACVD toolkit (https://github.com/valette/ACVD).

ACVDQ.exe MESH.VTK NBPOINTS 0 -d 0 -np NUMBERTHREADS -o OUTPUTDIR

Thus, your mesh will have a smooth appearance, the same number of points and equidistant triangles. This should help your registration process and increase the number of "good" correspondences. 

Best regards.

**Comment by marcelluethi** [comment] 2018-05-09 06:47
@guatavita Thanks for the information and especially also for the link. This sounds very useful. 

The problem of the "invisible" points in vtk also causes similar problem. However, the cause is different. The invisible points appear because of the way some vtk filters work, whereas the merged points in stl is caused by the representation of the data in the file format. As far as I know, the problem of merged points should not occur with VTK, as the data format is different and explicitly maintains a list of all the points (i.e. in contast to stl, it allows for duplicate points).

**Comment by guatavita** [comment] 2018-05-10 14:53
@marcelluethi I have investigated the merged point problem and indeed i could not find any solution. As you said, points are definitely lost between VTK and STL format in this particular case. 

Some VTK filter also create merged points (Smooting filters i think), it does not help either...

Best regards.

**Closed** 2019-07-26 05:37 UTC
Labels: discussion
