### ISSUE TITLE
Error: downloading unibas-gravis/scalismo-ui

### ISSUE THREAD

**Issue by jearice** [unibas-gravis/scalismo#412] opened 2023-10-02 14:35 UTC
hello,
My name is Jearice and I am a master student attempting to install scalismo on my laptop in order to use SSAM.
I am using a dell E5440 laptop with windows 10.
 
I am at the step where I am adding the dependency:
libraryDependencies += "ch.unibas.cs.gravis" %% "scalismo-ui" % "0.91.0"

and I then obtain the foolllowing error: "extracting structure failed: Build status: Error
check the root node of the tree for more details"

And when I look at the root node of the tree I see the following:

[error] stack trace is suppressed; run 'last ssExtractDependencies' for the full output
[error] (update) sbt.librarymanagement.ResolveException: Error downloading ch.unibas.cs.gravis:scalismo-ui_2.13:0.92.0
[error]   Not found
[error]   Not found
[error]   not found: C:\Users\Utilisateur\.ivy2\localch.unibas.cs.gravis\scalismo-ui_2.13\0.92.0\ivys\ivy.xml
[error]   not found: https://repo1.maven.org/maven2/ch/unibas/cs/gravis/scalismo-ui_2.13/0.92.0/scalismo-ui_2.13-0.92.0.pom
[error] (ssExtractDependencies) sbt.librarymanagement.ResolveException: Error downloading ch.unibas.cs.gravis:scalismo-ui_2.13:0.92.0
[error]   Not found
[error]   Not found
[error]   not found: C:\Users\Utilisateur\.ivy2\localch.unibas.cs.gravis\scalismo-ui_2.13\0.92.0\ivys\ivy.xml
[error]   not found: https://repo1.maven.org/maven2/ch/unibas/cs/gravis/scalismo-ui_2.13/0.92.0/scalismo-ui_2.13-0.92.0.pom
[error] Total time: 16 s, completed Oct 2, 2023, 3:58:20 PM
[info] shutting down sbt server

Can somebody please suggest me what to do in order to solve this and see the scalismo 
![Screenshot (47)](https://github.com/unibas-gravis/scalismo/assets/145420550/6daa257f-3d78-4367-9467-bd3e64b9789c)
gui?
would truly appreciate it.

**Comment by marcelluethi** [comment] 2023-10-02 15:06
Welcome to Scalismo.

I think the problem is that you are using scala 2.13 with the latest version of Scalismo-ui, which is only published for Scala 3.  The easiest way to get a working project is to start with the [template project (scalismo-seed)](https://github.com/unibas-gravis/scalismo-seed.g8/tree/master). Just follow the instructions in the readme and you should end up with a working skeleton project. 

If you really want to use Scala 2.13 with the latest Scalismo version, there is also a way to do it (see the [Scala3 migration guide](https://docs.scala-lang.org/scala3/guides/migration/compatibility-classpath.html). 


I will close this issue, as it is not really for support, but for technical problems with Scalismo. If you need more support, please write on our [mailing-list](https://groups.google.com/g/scalismo) instead.

**Closed by marcelluethi** 2023-10-02 15:06 UTC
