### ISSUE TITLE
Unexpected Behaviour when writing a mesh to an STL file in Scalismo 1.0

### ISSUE THREAD

**Issue by Floribur** [unibas-gravis/scalismo#429] opened 2024-05-06 18:08 UTC
Using the new `"ch.unibas.cs.gravis" %% "scalismo" % "1.0-RC1", or "1.0-SNAPSHOT" Scalismo 1.0 Release, writing a mesh as a .stl file seems to cause a problem. In contrast, a .ply file works as I would expect it to behave. Using the older Scalismo 0.92.1 release with VTK works as expected for both .stl and .ply files.

The problem is that the point IDs mismatch after writing a mesh to a .stl file and then reading it again. This is problematic since when one has established correspondence based on PointIds this can lead to unexpected behaviour after writing and then reading a mesh.

I have not verified whether this is a write or read problem. It also does not seem to be a general problem with all meshes, but just for some. 

Simple code snippet to reproduce the behaviour using the [sphere mesh](https://github.com/mikedh/trimesh/blob/main/models/sphere.ply ) from the trimesh package:

```
import scalismo.common.PointId
import scalismo.geometry._3D
import scalismo.io.MeshIO
import scalismo.mesh.TriangleMesh

import java.io.File

@main
def main(): Unit = {

  // If using 0.92.1, we need to initialize the scalismo library. For RC1, this is not necessary
  // scalismo.initialize()
  
  val mesh_input = MeshIO
    .readMesh(
      new File(s"data/sphere.ply")
    )
    .get

  val ply_file = new File(s"data/test.ply")
  val stl_file = new File(s"data/test.stl")

  // Write to disk as ply and stl
  MeshIO.writeMesh(
    mesh_input,
    ply_file
  )
  MeshIO.writeMesh(
    mesh_input,
    stl_file
  )

  // Read from disk as ply and stl
  val mesh_read_from_ply_file = MeshIO
    .readMesh(
      ply_file
    )
    .get

  val mesh_read_from_stl_file = MeshIO
    .readMesh(
      stl_file
    )
    .get

  // Check that the points are still the same for each point id
  println("Ply file check:")
  compareMeshes(mesh_input, mesh_read_from_ply_file)

  println("Stl file check:")
  compareMeshes(mesh_input, mesh_read_from_stl_file)
}

def compareMeshes(mesh1: TriangleMesh[_3D], mesh2: TriangleMesh[_3D]) : Unit = {
  for (i <- 0 until mesh1.pointSet.numberOfPoints) {
    val point = mesh1.pointSet.point(PointId(i))
    val point_2 = mesh2.pointSet.point(PointId(i))
    if ((point - point_2).norm > 1e-3) {
      println(s"Point $i is different")
      println(s"Point (mesh1): $point")
      println(s"Point (mesh2): $point_2")
    }
  }
}
```

The code snippet shows that the ply file keeps correspondence, but the STL file loses it. 
Example output:

```
Ply file check:
Stl file check:
Point 1 is different
Point (mesh1): Point3D(0.5076541210928077,0.8615212233036169,0.06492190478380781)
Point (mesh2): Point3D(-0.7280263900756836,0.6600714325904846,0.19782085716724396)
Point 2 is different
Point (mesh1): Point3D(-0.5257310271263123,-0.8506510257720947,0.0)
Point (mesh2): Point3D(-0.5316402316093445,0.8330438137054443,0.16889004409313202)
[...]
```

**Comment by Andreas-Forster** [comment] 2024-05-06 20:03
First, thank you for reporting this issue in such a comprehensive way.

I quickly checked the STL read/write code. It is really possible, that when a mesh is written for the first time, and read back in again, that then the points are no longer in the same order. The surface, however, should be the same. Any subsequent write/read cycle, after the first one, should not alter the mesh any further.

Background: This is due to that the writer processes the triangles in order, and writes the points for each triangle. The reader then reads back in the triangles and assigns the point IDs in ascending order to the points encountered. Hence, the new point with id=0 is the first point of the first triangle.

You mentioned, and I completely agree, that this is an unwanted behavior for a software establishing point correspondence among others. We should find a way how the missing information about the point IDs can be stored in the STL format, and fix the reader/writer.

**Comment by madsendennis** [comment] 2024-05-07 10:40
Thank you for highlighting this problem. 
In general, I always advocate to use the .ply format when dealing with meshes in correspondence. Even with the .stl reader from vtk I've had problems if multiple points have the same location that they might then be merged. In the stl format, point order is only implicitly given through the triangles. 

With that said, I agree with Andreas that this should still be fixed. I think a solution could be to order the triangle list either when writing the mesh.
In the current version, I think that it might assume that the first triangle also contains the points with the lowest point ids. But I'll have to take a look first.

**Comment by madsendennis** [comment] 2024-05-08 14:32
I cannot reproduce the behavior you see, @Floribur. To me, the result is the same whether I use the old or new Scalismo version with your code example. 
Btw. the vtk read/writers are also available in the new scalismo through scalismo-vtk. 
Then you just need to change `import scalismo.io.MeshIO` to `import scalismo.vtk.io.MeshIO` and use `scalismo.vtk.initialize()`. 

I also checked the behaviour with MeshLab with the same result. In there I:
- Read provided PLY file
- Write mesh to STL file
- Read mesh from STL file
- Write mesh to PLY file
If you write to an ASCII file, you can directly compare the PLY output with the original and see that the point order changed .

For me, the first 3 points changed from:
```
end_header
-0.525731 0.850651 0 
0.525731 0.850651 0 
-0.525731 -0.850651 0 
```
to
```
end_header
-0.525731 0.850651 0 
-0.615642 0.783843 0.0810863 
-0.484442 0.864929 0.1312 
```
Unfortunately, the behavior you see is due to the STL file format not encoding the point ID explicitly. 
So to me, there is not really a fix for this "problem", do you have something to add @Andreas-Forster ?

**Comment by Andreas-Forster** [comment] 2024-05-08 15:20
Reading up on STL, I think it is not possible to fix this bug. However, if you have to use STL, there might be a workaround. If STL is not a strict requirement, use ply instead.

Based on the specification, there is no possibility to add the needed information on the original order of points, in the STL file when writing. When reading the file back in, the order of the points is determined by the order they appear in the triangle list. Hence, we can not fix this bug.

However, the process of writing and reading always produces the same result after the first cycle. Hence, a workaround could be, that each STL mesh is first once written and read in again before using it for anything else.

The workaround of course can't fix broken correspondence, to what ever was before (already existing information or other software). There, only a post-processing step, mapping between point correspondences, could help fixing this.

**Comment by Andreas-Forster** [comment] 2024-05-08 15:21
As we can't do here anything, I will close this issue.

**Closed as completed by Andreas-Forster** 2024-05-08 15:21 UTC
Labels: bug, wontfix
